# Generated by Django 3.2.9 on 2021-12-07 09:45

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0011_delete_interaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_of_reference', models.CharField(blank=True, choices=[('Request', 'Request'), ('Letter', 'Letter'), ('Web site', 'Web site'), ('Company init.', 'Company initiates')], default='Request', help_text='Interaction way', max_length=15)),
                ('description', ckeditor.fields.RichTextField(help_text='Describe the interaction')),
                ('grade', models.CharField(blank=True, choices=[('-5', '-5'), ('-4', '-4'), ('-3', '-3'), ('-2', '-2'), ('-1', '-1'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', help_text='Interaction grade', max_length=2)),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('date_of_edition', models.DateField(auto_now=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.customer')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project')),
            ],
        ),
    ]
