# Generated by Django 3.2.9 on 2021-12-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0002_remove_interaction_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='date_of_edition',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
