# Generated by Django 3.2.9 on 2021-12-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0003_auto_20211208_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='channel_of_reference',
            field=models.CharField(blank=True, choices=[('RQ', 'Request'), ('LT', 'Letter'), ('WS', 'Web site'), ('CI', 'Company initiates')], default='RQ', help_text='Interaction way', max_length=2),
        ),
    ]
