# Generated by Django 3.2.9 on 2021-12-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0004_alter_interaction_channel_of_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='channel_of_reference',
            field=models.CharField(blank=True, choices=[('Request', 'Request'), ('Letter', 'Letter'), ('Web site', 'Web site'), ('Company init.', 'Company initiates')], default='Request', help_text='Interaction way', max_length=15),
        ),
    ]
