# Generated by Django 3.2.9 on 2021-12-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0005_alter_interaction_channel_of_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='channel_of_reference',
            field=models.CharField(blank=True, choices=[('RQ', 'Request'), ('LT', 'Letter'), ('WS', 'Web site'), ('CI', 'Company initiates')], default='REQUEST', help_text='Interaction way', max_length=2),
        ),
    ]
