# Generated by Django 3.1 on 2021-12-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0005_alter_interaction_channel_of_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='channel_of_reference',
            field=models.CharField(blank=True, choices=[('Request', 'Request'), ('Letter', 'Letter'), ('Web site', 'Web site'), ('Company init.', 'Company initiates')], default='REQUEST', help_text='Interaction way', max_length=15),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1'), (-1, '-1'), (-2, '-2'), (-3, '-3'), (-4, '-4'), (-5, '-5')], default='ONE', help_text='Interaction grade'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
