# Generated by Django 3.2.9 on 2021-12-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0007_alter_interaction_channel_of_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, help_text='Interaction grade', max_length=2),
        ),
    ]
