# Generated by Django 3.2.9 on 2021-12-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0008_alter_interaction_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1'), (-1, '-1'), (-2, '-2'), (-3, '-3'), (-4, '-4'), (-5, '-5')], default='ONE', help_text='Interaction grade'),
        ),
    ]
