# Generated by Django 3.2.9 on 2021-12-07 08:20

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', ckeditor.fields.RichTextField()),
                ('begin_date', models.DateField(default=datetime.date.today, help_text='Project start date')),
                ('end_date', models.DateField(blank=True, help_text='Project end date', null=True)),
                ('price', models.FloatField()),
            ],
        ),
    ]
