# Generated by Django 3.2.9 on 2021-12-03 07:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20211202_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='descriptions',
            field=ckeditor.fields.RichTextField(help_text='Describe the company'),
        ),
    ]
