# Generated by Django 3.2.9 on 2021-12-04 13:11

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0004_alter_customer_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project title', max_length=300)),
                ('description', ckeditor.fields.RichTextField(help_text='Describe the project')),
                ('begin_date', models.DateField(default=datetime.date.today, help_text='Project start date')),
                ('end_date', models.DateField(blank=True, help_text='Project end date', null=True)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='adress',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(help_text='Address of the organization', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(help_text='Company name', max_length=300),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.ManyToManyField(help_text='Email(s)', to='catalog.Email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='foreman_name',
            field=models.CharField(help_text="Foreman's name", max_length=300),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.ManyToManyField(help_text='Phone number(s)', to='catalog.Phone'),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(help_text='Email', max_length=254),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(help_text='Phone number', max_length=30),
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_of_reference', models.CharField(blank=True, choices=[('r', 'Request'), ('l', 'Letter'), ('w', 'Web site'), ('c', 'Company init.')], default='r', help_text='Interaction way', max_length=1)),
                ('description', ckeditor.fields.RichTextField(help_text='Describe the interaction')),
                ('grade', models.DecimalField(blank=True, choices=[(-5, '-5'), (-4, '-4'), (-3, '-3'), (-2, '-2'), (-1, '-1'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], decimal_places=2, default=1, help_text='Interaction grade', max_digits=2)),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('date_of_edition', models.DateField(auto_now=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.customer')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.project')),
            ],
        ),
    ]
