# Generated by Django 3.2.9 on 2021-12-07 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('catalog', '0009_alter_interaction_channel_of_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
