# Generated by Django 3.2.9 on 2021-12-07 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20211207_0820'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interaction',
        ),
    ]
